name: jmstoolbox-snap # you probably want to 'snapcraft register <name>'
version: 'latest' # just for humans, typically '1.2+git' or '1.3.2'
summary: JMSToolBox is an Universal JMS Client able to interact with Queue Managers. # 79 char long summary
description: |
  JMSToolBox is a JMS Client able to interact with Queue Managers/Queue providers, written in Java. Browse, Post, Remove, Move messages to/from Queues and Topics

confinement: devmode # use 'strict' once you have the right plugs and slots

#parts:
#  my-part:
    # See 'snapcraft plugins'
#    plugin: nil

parts:
  jmstoolbox:
    after: [desktop-gtk2]
    plugin: dump
    source-type: tar
    source: https://api.github.com/repos/jmstoolbox/jmstoolbox/tarball
    build-packages:
     - jshon
    override-build: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr/share/JMSToolBox
     mv app/* $SNAPCRAFT_PART_INSTALL/usr/share/JMSToolBox
     VERSION=$(cat $SNAPCRAFT_PART_INSTALL/usr/share/JMSToolBox/resources/app/package.json | jshon -e version | sed 's/\"//g')
     echo $VERSION > $SNAPCRAFT_STAGE/version
    stage:
     - usr/*
    stage-packages:
      - libasound2
      - libatomic1
      - libc++1
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6
      - libdb5.3

  desktop:
    after: [jmstoolbox]
    plugin: dump
    source: .
    override-build: |
     mkdir $SNAPCRAFT_PART_INSTALL/usr $SNAPCRAFT_PART_INSTALL/usr/share $SNAPCRAFT_PART_INSTALL/usr/share/applications
     mv jmstoolbox.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications
    stage:
     - usr/share/applications/JMSToolBox.desktop

apps:
  postman:
    command: bin/desktop-launch $SNAP/usr/share/JMSToolBox/JMSToolBox
    desktop: usr/share/applications/JMSToolBox.desktop
    plugs: [home, network, network-observe, x11, wayland, opengl, desktop, desktop-legacy, unity7, gsettings, browser-support]
